apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    name: db-noticias
spec:  
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap
        
      
